version: "3.9"
services:
  migrate:
    build: .
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_started
    command: alembic upgrade head

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
